// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.33
// source: blockchain_node.proto

package blockchain

import (
	context "context"
	errors "errors"
	drpc1 "github.com/planetscale/vtprotobuf/codec/drpc"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_blockchain_node_proto struct{}

func (drpcEncoding_File_blockchain_node_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return drpc1.Marshal(msg)
}

func (drpcEncoding_File_blockchain_node_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.Unmarshal(buf, msg)
}

func (drpcEncoding_File_blockchain_node_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return drpc1.JSONMarshal(msg)
}

func (drpcEncoding_File_blockchain_node_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.JSONUnmarshal(buf, msg)
}

type DRPCBlockchainNodeClient interface {
	DRPCConn() drpc.Conn

	Receive(ctx context.Context) (DRPCBlockchainNode_ReceiveClient, error)
}

type drpcBlockchainNodeClient struct {
	cc drpc.Conn
}

func NewDRPCBlockchainNodeClient(cc drpc.Conn) DRPCBlockchainNodeClient {
	return &drpcBlockchainNodeClient{cc}
}

func (c *drpcBlockchainNodeClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcBlockchainNodeClient) Receive(ctx context.Context) (DRPCBlockchainNode_ReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, "/blockchain.BlockchainNode/Receive", drpcEncoding_File_blockchain_node_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcBlockchainNode_ReceiveClient{stream}
	return x, nil
}

type DRPCBlockchainNode_ReceiveClient interface {
	drpc.Stream
	Send(*Packet) error
	Recv() (*Packet, error)
}

type drpcBlockchainNode_ReceiveClient struct {
	drpc.Stream
}

func (x *drpcBlockchainNode_ReceiveClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcBlockchainNode_ReceiveClient) Send(m *Packet) error {
	return x.MsgSend(m, drpcEncoding_File_blockchain_node_proto{})
}

func (x *drpcBlockchainNode_ReceiveClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.MsgRecv(m, drpcEncoding_File_blockchain_node_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcBlockchainNode_ReceiveClient) RecvMsg(m *Packet) error {
	return x.MsgRecv(m, drpcEncoding_File_blockchain_node_proto{})
}

type DRPCBlockchainNodeServer interface {
	Receive(DRPCBlockchainNode_ReceiveStream) error
}

type DRPCBlockchainNodeUnimplementedServer struct{}

func (s *DRPCBlockchainNodeUnimplementedServer) Receive(DRPCBlockchainNode_ReceiveStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCBlockchainNodeDescription struct{}

func (DRPCBlockchainNodeDescription) NumMethods() int { return 1 }

func (DRPCBlockchainNodeDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/blockchain.BlockchainNode/Receive", drpcEncoding_File_blockchain_node_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCBlockchainNodeServer).
					Receive(
						&drpcBlockchainNode_ReceiveStream{in1.(drpc.Stream)},
					)
			}, DRPCBlockchainNodeServer.Receive, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterBlockchainNode(mux drpc.Mux, impl DRPCBlockchainNodeServer) error {
	return mux.Register(impl, DRPCBlockchainNodeDescription{})
}

type DRPCBlockchainNode_ReceiveStream interface {
	drpc.Stream
	Send(*Packet) error
	Recv() (*Packet, error)
}

type drpcBlockchainNode_ReceiveStream struct {
	drpc.Stream
}

func (x *drpcBlockchainNode_ReceiveStream) Send(m *Packet) error {
	return x.MsgSend(m, drpcEncoding_File_blockchain_node_proto{})
}

func (x *drpcBlockchainNode_ReceiveStream) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.MsgRecv(m, drpcEncoding_File_blockchain_node_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcBlockchainNode_ReceiveStream) RecvMsg(m *Packet) error {
	return x.MsgRecv(m, drpcEncoding_File_blockchain_node_proto{})
}
