// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.33
// source: node.proto

package blockchain

import (
	context "context"
	errors "errors"
	drpc1 "github.com/planetscale/vtprotobuf/codec/drpc"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_node_proto struct{}

func (drpcEncoding_File_node_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return drpc1.Marshal(msg)
}

func (drpcEncoding_File_node_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.Unmarshal(buf, msg)
}

func (drpcEncoding_File_node_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return drpc1.JSONMarshal(msg)
}

func (drpcEncoding_File_node_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.JSONUnmarshal(buf, msg)
}

type DRPCNodeClient interface {
	DRPCConn() drpc.Conn

	Receive(ctx context.Context) (DRPCNode_ReceiveClient, error)
}

type drpcNodeClient struct {
	cc drpc.Conn
}

func NewDRPCNodeClient(cc drpc.Conn) DRPCNodeClient {
	return &drpcNodeClient{cc}
}

func (c *drpcNodeClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcNodeClient) Receive(ctx context.Context) (DRPCNode_ReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, "/node.Node/Receive", drpcEncoding_File_node_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcNode_ReceiveClient{stream}
	return x, nil
}

type DRPCNode_ReceiveClient interface {
	drpc.Stream
	Send(*BlockchainMessage) error
	Recv() (*BlockchainMessage, error)
}

type drpcNode_ReceiveClient struct {
	drpc.Stream
}

func (x *drpcNode_ReceiveClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcNode_ReceiveClient) Send(m *BlockchainMessage) error {
	return x.MsgSend(m, drpcEncoding_File_node_proto{})
}

func (x *drpcNode_ReceiveClient) Recv() (*BlockchainMessage, error) {
	m := new(BlockchainMessage)
	if err := x.MsgRecv(m, drpcEncoding_File_node_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcNode_ReceiveClient) RecvMsg(m *BlockchainMessage) error {
	return x.MsgRecv(m, drpcEncoding_File_node_proto{})
}

type DRPCNodeServer interface {
	Receive(DRPCNode_ReceiveStream) error
}

type DRPCNodeUnimplementedServer struct{}

func (s *DRPCNodeUnimplementedServer) Receive(DRPCNode_ReceiveStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCNodeDescription struct{}

func (DRPCNodeDescription) NumMethods() int { return 1 }

func (DRPCNodeDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/node.Node/Receive", drpcEncoding_File_node_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCNodeServer).
					Receive(
						&drpcNode_ReceiveStream{in1.(drpc.Stream)},
					)
			}, DRPCNodeServer.Receive, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterNode(mux drpc.Mux, impl DRPCNodeServer) error {
	return mux.Register(impl, DRPCNodeDescription{})
}

type DRPCNode_ReceiveStream interface {
	drpc.Stream
	Send(*BlockchainMessage) error
	Recv() (*BlockchainMessage, error)
}

type drpcNode_ReceiveStream struct {
	drpc.Stream
}

func (x *drpcNode_ReceiveStream) Send(m *BlockchainMessage) error {
	return x.MsgSend(m, drpcEncoding_File_node_proto{})
}

func (x *drpcNode_ReceiveStream) Recv() (*BlockchainMessage, error) {
	m := new(BlockchainMessage)
	if err := x.MsgRecv(m, drpcEncoding_File_node_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcNode_ReceiveStream) RecvMsg(m *BlockchainMessage) error {
	return x.MsgRecv(m, drpcEncoding_File_node_proto{})
}
