// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.33
// source: peer_manager.proto

package blockchain

import (
	context "context"
	errors "errors"
	drpc1 "github.com/planetscale/vtprotobuf/codec/drpc"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_peer_manager_proto struct{}

func (drpcEncoding_File_peer_manager_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return drpc1.Marshal(msg)
}

func (drpcEncoding_File_peer_manager_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.Unmarshal(buf, msg)
}

func (drpcEncoding_File_peer_manager_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return drpc1.JSONMarshal(msg)
}

func (drpcEncoding_File_peer_manager_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.JSONUnmarshal(buf, msg)
}

type DRPCPeerManagerClient interface {
	DRPCConn() drpc.Conn

	Receive(ctx context.Context) (DRPCPeerManager_ReceiveClient, error)
}

type drpcPeerManagerClient struct {
	cc drpc.Conn
}

func NewDRPCPeerManagerClient(cc drpc.Conn) DRPCPeerManagerClient {
	return &drpcPeerManagerClient{cc}
}

func (c *drpcPeerManagerClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcPeerManagerClient) Receive(ctx context.Context) (DRPCPeerManager_ReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, "/blockchain.PeerManager/Receive", drpcEncoding_File_peer_manager_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcPeerManager_ReceiveClient{stream}
	return x, nil
}

type DRPCPeerManager_ReceiveClient interface {
	drpc.Stream
	Send(*BlockchainMessage) error
	Recv() (*BlockchainMessage, error)
}

type drpcPeerManager_ReceiveClient struct {
	drpc.Stream
}

func (x *drpcPeerManager_ReceiveClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcPeerManager_ReceiveClient) Send(m *BlockchainMessage) error {
	return x.MsgSend(m, drpcEncoding_File_peer_manager_proto{})
}

func (x *drpcPeerManager_ReceiveClient) Recv() (*BlockchainMessage, error) {
	m := new(BlockchainMessage)
	if err := x.MsgRecv(m, drpcEncoding_File_peer_manager_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcPeerManager_ReceiveClient) RecvMsg(m *BlockchainMessage) error {
	return x.MsgRecv(m, drpcEncoding_File_peer_manager_proto{})
}

type DRPCPeerManagerServer interface {
	Receive(DRPCPeerManager_ReceiveStream) error
}

type DRPCPeerManagerUnimplementedServer struct{}

func (s *DRPCPeerManagerUnimplementedServer) Receive(DRPCPeerManager_ReceiveStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCPeerManagerDescription struct{}

func (DRPCPeerManagerDescription) NumMethods() int { return 1 }

func (DRPCPeerManagerDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/blockchain.PeerManager/Receive", drpcEncoding_File_peer_manager_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCPeerManagerServer).
					Receive(
						&drpcPeerManager_ReceiveStream{in1.(drpc.Stream)},
					)
			}, DRPCPeerManagerServer.Receive, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterPeerManager(mux drpc.Mux, impl DRPCPeerManagerServer) error {
	return mux.Register(impl, DRPCPeerManagerDescription{})
}

type DRPCPeerManager_ReceiveStream interface {
	drpc.Stream
	Send(*BlockchainMessage) error
	Recv() (*BlockchainMessage, error)
}

type drpcPeerManager_ReceiveStream struct {
	drpc.Stream
}

func (x *drpcPeerManager_ReceiveStream) Send(m *BlockchainMessage) error {
	return x.MsgSend(m, drpcEncoding_File_peer_manager_proto{})
}

func (x *drpcPeerManager_ReceiveStream) Recv() (*BlockchainMessage, error) {
	m := new(BlockchainMessage)
	if err := x.MsgRecv(m, drpcEncoding_File_peer_manager_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcPeerManager_ReceiveStream) RecvMsg(m *BlockchainMessage) error {
	return x.MsgRecv(m, drpcEncoding_File_peer_manager_proto{})
}
