env: "dev"
version: 1
mining_reward: 1
mining_sender: "cluster"
mining_difficulty : 5
mining_timer_sec: 20
max_node_heartbeat_misses: 5
max_cluster_heartbeat_misses: 3
member_join_timeout: 10
heartbeat_timeout: 10
node_heartbeat_interval_ms: 1000
cluster_heartbeat_interval_ms: 1000
min_leader_election_ms: 200
max_leader_election_ms: 300
node_recover_timeout_ms: 300